import type { PageMetadata } from "@/themes"

export const metadata: PageMetadata = {
  title: "Privacy Policy — Super Engineered",
  description: "How Super Engineered handles data from your essential objects.",
}

export default function SuperEngineeredPrivacy() {
  return (
    <main className="bg-background py-20 px-4">
      <article className="max-w-3xl mx-auto">
        <p className="text-sm font-medium uppercase tracking-widest text-primary/60 mb-4">
          Legal
        </p>
        <h1 className="text-4xl font-heading font-light text-primary mb-10">
          Privacy Policy
        </h1>
        <div className="space-y-6 text-primary/80 leading-relaxed">
          <p className="text-sm text-primary/50">Last updated: 2026-04-17</p>
          <p>
            Super Engineered, Inc. (&ldquo;we&rdquo;) processes data generated by your essential objects — including but not limited to brushing telemetry, doorknob turn logs, light-switch authentication events, and spoon usage analytics — in order to deliver the product experience you have subscribed to.
          </p>
          <h2 className="text-2xl font-heading font-light text-primary mt-8 mb-3">
            Data We Collect
          </h2>
          <p>
            We collect device identifiers, usage patterns, biometric signatures (where opted in), ambient environmental readings, and derived ML features. In aggregate, this is sometimes referred to as your &ldquo;telemetry estate.&rdquo;
          </p>
          <h2 className="text-2xl font-heading font-light text-primary mt-8 mb-3">
            How We Use It
          </h2>
          <p>
            To provide, maintain, and improve our products; to enforce subscription entitlements; to produce compliance reports at enterprise scale; and to train successor firmware.
          </p>
          <h2 className="text-2xl font-heading font-light text-primary mt-8 mb-3">
            Retention
          </h2>
          <p>
            Telemetry is retained for the life of your subscription plus seven years. Upon cancellation, device hardware enters lockout mode within 30 days.
          </p>
          <h2 className="text-2xl font-heading font-light text-primary mt-8 mb-3">
            Your Rights
          </h2>
          <p>
            Under applicable privacy regulation (GDPR, CCPA, and successor frameworks), you have the right to request access, correction, or deletion of your telemetry. Deletion requests may take up to 90 days to propagate across our mesh.
          </p>
          <h2 className="text-2xl font-heading font-light text-primary mt-8 mb-3">
            Contact
          </h2>
          <p>
            Direct privacy inquiries to <a href="mailto:privacy@superengineered.example" className="text-accent hover:underline">privacy@superengineered.example</a>.
          </p>
        </div>
      </article>
    </main>
  )
}
