import Link from "next/link"
import type { PageMetadata } from "@/themes"

export const metadata: PageMetadata = {
  title: "Trust & Safety — Superengineered",
  description: "How Superengineered stewards the telemetry generated by your essential objects.",
}

const certifications = [
  "SOC 2 Type II",
  "ISO 27001",
  "HIPAA",
  "GDPR",
  "CCPA",
  "PCI DSS 4.0",
  "FedRAMP (in progress)",
]

export default function SuperengineeredTrust() {
  return (
    <main className="bg-background">
      <section className="py-20 px-4 text-center">
        <p className="text-sm font-medium uppercase tracking-widest text-primary/60 mb-4">
          Trust & Safety
        </p>
        <h1 className="text-5xl md:text-6xl font-heading font-light text-primary mb-4">
          Your telemetry, stewarded.
        </h1>
        <p className="text-xl text-primary/70 max-w-3xl mx-auto">
          Every brush. Every turn. Every tap. Every bite. Encrypted in transit. Encrypted at rest. Retained only as long as our terms require.
        </p>
      </section>

      <section className="bg-secondary py-16 px-4">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-sm font-medium uppercase tracking-widest text-primary/60 mb-2 text-center">
            Certifications
          </h2>
          <p className="text-3xl md:text-4xl font-heading font-light text-primary text-center mb-10">
            Audited by humans you will never meet.
          </p>
          <div className="flex flex-wrap gap-3 justify-center">
            {certifications.map((c) => (
              <span key={c} className="bg-background text-primary px-4 py-2 rounded-full text-sm font-medium">
                {c}
              </span>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 px-4">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-heading font-light text-primary mb-8">
            Where your data lives.
          </h2>
          <div className="space-y-6 text-primary/80 leading-relaxed">
            <p>
              Telemetry from your Superengineered devices is ingested through regional edge pops and consolidated into two geo-redundant data planes in the United States and the European Union.
            </p>
            <p>
              We apply AES-256 encryption at rest and mutual TLS 1.3 in transit. Per-customer encryption keys are rotated every 90 days, managed via our internal HSM fleet.
            </p>
            <p>
              Data is retained for the duration of your subscription plus seven years thereafter. Upon cancellation, device hardware enters lockout mode within 30 days; telemetry is retained for legal and compliance reasons per our Terms.
            </p>
          </div>
        </div>
      </section>

      <section className="bg-primary text-background py-20 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-heading font-light mb-4">
            Release Notes — Firmware 4.2
          </h2>
          <ul className="text-left space-y-3 max-w-xl mx-auto text-background/80">
            <li>&bull; Improved predictive bristle alignment on Toothbrush Pro and Pro Max.</li>
            <li>&bull; Recertified doorknob torque curves (addresses CVE-2026-0041).</li>
            <li>&bull; Light switch authentication latency reduced by 12%.</li>
            <li>&bull; Spoon bowl volume precision improved to 0.1 mL.</li>
            <li>&bull; Legacy Toothbrush Standard units on firmware &lt;4.0 deprecated. Contact support for replacement pricing.</li>
          </ul>
          <Link
            href="/contact"
            className="inline-block mt-10 px-6 py-3 rounded-full bg-accent text-white font-medium hover:opacity-90 transition-opacity"
          >
            Report a trust incident
          </Link>
        </div>
      </section>
    </main>
  )
}
