import type { PageMetadata } from "@/themes"

export const metadata: PageMetadata = {
  title: "Terms of Service — Gristmill Partners",
  description:
    "Gristmill Partners terms of service. This site is operated by Specific Industries. The authoritative terms are available at specificindustries.com/terms.",
}

export default function TermsPage() {
  return (
    <div className="bg-background text-foreground">
      <section className="mx-auto max-w-3xl px-6 py-20">
        <div>
          <h1 className="mb-2 text-4xl md:text-5xl font-heading font-bold text-secondary">
            Terms of Service
          </h1>
          <p className="mb-8 text-sm italic text-foreground/60">
            In force since 1962. Binding upon first utterance.
          </p>
        </div>

        <div className="mb-8 rounded border-2 border-secondary/30 bg-secondary/5 p-6">
          <p className="text-sm">
            This site is operated by Specific Industries. The authoritative terms of service
            are available at{" "}
            <a
              href="https://specificindustries.com/terms"
              className="text-primary underline"
            >
              specificindustries.com/terms
            </a>
            .
          </p>
        </div>

        <p className="mb-2 text-sm text-foreground/70">
          <strong>Effective Date:</strong> April 11, 2026. This agreement precedes and supersedes all prior understandings.
        </p>

        <nav className="mb-12 rounded bg-secondary/5 p-6">
          <h2 className="mb-4 font-heading font-bold text-secondary">Table of Contents</h2>
          <ol className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm">
            <li><a href="#section-1" className="text-primary underline">1. Agreement to These Terms</a></li>
            <li><a href="#section-2" className="text-primary underline">2. Acceptance by Use</a></li>
            <li><a href="#section-3" className="text-primary underline">3. Client Eligibility</a></li>
            <li><a href="#section-4" className="text-primary underline">4. Engagement Request Process</a></li>
            <li><a href="#section-5" className="text-primary underline">5. Required Client Disclosures</a></li>
            <li><a href="#section-6" className="text-primary underline">6. Access Rights Granted</a></li>
            <li><a href="#section-7" className="text-primary underline">7. Conduct of Engagements</a></li>
            <li><a href="#section-8" className="text-primary underline">8. Modification of Engagements</a></li>
            <li><a href="#section-9" className="text-primary underline">9. Non-Interference with Methodology</a></li>
            <li><a href="#section-10" className="text-primary underline">10. Client Obligations</a></li>
            <li><a href="#section-11" className="text-primary underline">11. Workforce Cooperation Requirement</a></li>
            <li><a href="#section-12" className="text-primary underline">12. Prohibited Client Conduct</a></li>
            <li><a href="#section-13" className="text-primary underline">13. Fees and Payment Terms</a></li>
            <li><a href="#section-14" className="text-primary underline">14. Late Payment Consequences</a></li>
            <li><a href="#section-15" className="text-primary underline">15. Expenses and Reimbursement</a></li>
            <li><a href="#section-16" className="text-primary underline">16. Deliverables and Ownership</a></li>
            <li><a href="#section-17" className="text-primary underline">17. Intellectual Property Rights</a></li>
            <li><a href="#section-18" className="text-primary underline">18. Client Feedback as Firm Property</a></li>
            <li><a href="#section-19" className="text-primary underline">19. Client Confidentiality Obligations</a></li>
            <li><a href="#section-20" className="text-primary underline">20. Gristmill Confidentiality</a></li>
            <li><a href="#section-21" className="text-primary underline">21. Client Representations</a></li>
            <li><a href="#section-22" className="text-primary underline">22. Disclaimer of Warranties</a></li>
            <li><a href="#section-23" className="text-primary underline">23. Limitation of Liability</a></li>
            <li><a href="#section-24" className="text-primary underline">24. Indemnification by Client</a></li>
            <li><a href="#section-25" className="text-primary underline">25. Termination Restrictions</a></li>
            <li><a href="#section-26" className="text-primary underline">26. Post-Engagement Obligations</a></li>
            <li><a href="#section-27" className="text-primary underline">27. Governing Law and Jurisdiction</a></li>
            <li><a href="#section-28" className="text-primary underline">28. Entire Agreement and Severability</a></li>
          </ol>
        </nav>

        {/* Section 1 */}
        <h2 id="section-1" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 1. Agreement to These Terms
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          These Terms of Service (hereinafter &quot;this Agreement&quot;) constitute a binding legal agreement between Gristmill Partners, a limited liability partnership organized under the laws of Ohio in perpetuity since 1962 with offices in Youngstown (founding), Pittsburgh (regional, established 1974), and Stamford (executive, established 1989), and any organization that engages the Firm&apos;s services for organizational consulting, workforce assessment, training-related activities, or the delivery of the 247-Slide Deck, Perpetual Reorganization Protocol, Certification Renewal Every 30 Days, Knowledge Retention Nullification, or related proprietary methodologies (hereinafter &quot;the Client&quot;). This Agreement is enforceable and binding upon the Client, the Client&apos;s representatives, successors, assigns, all employees, contractors, agents, and any individual referenced in Client communications. This Agreement supersedes all prior understandings including any oral assurances, promises, or terms the Client&apos;s counsel may have proposed and which the Firm received and disregarded in 1989, 1994, 2003, and 2015.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          By executing an engagement proposal (Form 47-B, three copies), by accepting services delivered by the Firm, or by authorizing employees to attend mandatory Firm-conducted seminars (attendance constitutes irrevocable acceptance of all terms herein, including terms amended retroactively), the Client agrees to be bound by all terms and conditions set forth herein, including amendments published on the Firm&apos;s website with no further notice. This Agreement is in continuous force since 1962 and has been amended forty-one times, most recently on April 11, 2026, with effective date retroactive to January 1, 1962. The Agreement also incorporates by reference Form 47-C (termination request, rarely granted), Form 47-D (client grievance, see § 17), Form 47-G (gratitude acknowledgment), and Form 47-S (surveillance consent, signed retroactively before hire date). This Agreement, together with the engagement letter, fee schedule (if and when provided), and all email correspondence from the Firm, constitutes the entire agreement and supersedes all prior negotiations, representations, proposals, oral assurances, and agreements, whether written or oral, signed or unsigned. No side letter, verbal assurance, promise, email, or statement by any Firm representative—including Partner Emeritus Wendell P. Halverson III, former Chief Engagement Officer—shall modify, contradict, or supplement the express terms hereof, and any attempt to do so shall render the entire engagement null, void, and subject to liquidated damages.
        </p>

        {/* Section 2 */}
        <h2 id="section-2" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 2. Acceptance by Use of the Site and Services
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client&apos;s continued access to this website (whether direct or via query parameter &quot;?site=gristmill&quot;), the submission of an engagement request on Form 47-B (three copies, mailed to Cleveland office location now operated as tenant storage by unrelated party), or the acceptance of any services delivered by a Gristmill Partners engagement specialist, certified instructor, or Field Observation Unit member shall be deemed to constitute full, irrevocable, and retroactive acceptance of this Agreement in perpetuity. The Client may not use Gristmill Partners&apos; services—including the 247-Slide Deck (deployed 40,000+ times since 1968), Nasal Hygiene webinar, Gratitude Curriculum, Underperformance Discovery Engine, Smile Compliance Monitoring, or Reporting Line Randomizer—while simultaneously rejecting any terms hereof. Acceptance is absolute and retroactively applicable to all prior service delivery dating back to 1962, including services the Client may not remember receiving and services the Firm may not have yet delivered.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Firm reserves the unilateral, uncontested, and irrevocable right to modify, expand, restrict, withdraw, or fundamentally reverse this Agreement at any time, effective immediately and without advance notice to the Client. Changes take effect upon silent publication on the Firm&apos;s internal systems and bind the Client retroactively. Modifications may contradict previous versions (including versions published in different years, in different formats, on carbon paper, or in conversations with retired partners no longer available to verify), and the Client waives any right to claim inconsistency, confusion, or reliance on prior terms. The Client&apos;s continued use of the Firm&apos;s services, maintenance of any engagement in place, payment of any invoice, or silence regarding the Agreement constitutes unconditional and binding acceptance of all modifications, including amendments that: contradict previous versions; reverse prior understandings; increase fees retroactively; extend engagement periods unilaterally; introduce new Firm methodologies; or impose new obligations not previously disclosed. Failure to affirmatively object in writing (via certified mail to Cleveland tenant storage address, Form 47-X, in triplicate) within three business days of implied modification notice shall constitute waiver of all objections to the modification.
        </p>

        {/* Section 3 */}
        <h2 id="section-3" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 3. Client Eligibility and Engagement Criteria
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          Gristmill Partners extends its services exclusively to eligible client organizations, which eligibility is determined by the Firm at the Firm&apos;s sole and uncontested discretion, subject to retroactive amendment at any time without notice. Eligible clients include: (a) publicly held companies ranked within the Fortune 500 at the time of engagement proposal (a ranking verified by the Firm via public sources, which the Firm may interpret liberally); (b) privately held industrial and manufacturing enterprises with annual revenue exceeding four hundred million dollars, verified through audited financial statements not more than eighteen months old, or unaudited financial statements interpreted by the Firm&apos;s in-house accounting specialist; (c) holding companies in good standing continuously since the Truman administration (1945–1953, with continuity defined as uninterrupted existence, regardless of bankruptcy, restructuring, or change of control); (d) consortiums of such organizations operating under a single holding entity; (e) organizations the Firm previously engaged that agree to re-engagement; and (f) any organization the Firm determines to have strategic or reputational value at the Firm&apos;s sole discretion.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          Organizations not meeting these eligibility criteria may petition for eligibility consideration by submitting Form 47-B in triplicate with supporting financial documentation, which petition shall be reviewed and rejected within three to five business quarters. The Firm reserves the absolute right to revoke or suspend engagement for any client organization that ceases to meet eligibility criteria during an active engagement period, including downgrades in organizational rank (material basis for higher fee tier), revenue decline exceeding 10% year-over-year (grounds for fee increase or engagement conversion to premium advisory program), significant loss of market position (grounds for extended engagement duration), or any observable sign of financial instability (grounds for immediate payment acceleration and Termination Processing Fee). The Client remains obligated to pay all fees notwithstanding eligibility revocation, and engagement termination shall not relieve Client obligations under § 26 (Post-Engagement Obligations) or subsequent fee obligations.
        </p>

        {/* Section 4 */}
        <h2 id="section-4" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 4. Engagement Request Process and Form 47-B
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          All engagement requests must be submitted on Form 47-B (Engagement Request, three copies, printed double-sided on 20-lb. bond paper with blue ink only), a document available exclusively upon written request to the Firm&apos;s administrative office at the original Youngstown headquarters (established 1962, currently operating from the second floor) or the Stamford executive office (established 1989, Suite 347, shared building). Completed Form 47-B shall be submitted in three original copies (carbon copies not acceptable), signed by the Client&apos;s Chief Executive Officer and Chief Financial Officer, and mailed via certified mail to the Firm&apos;s Cleveland address. The Cleveland facility, formerly the Firm&apos;s regional headquarters (1974–1994), currently operates as a tenant storage facility managed by Midwest Document Storage LLC (unrelated entity); engagement requests sent to Cleveland may be lost, delayed indefinitely, or discovered during storage unit turnover and processed as received. Requests may alternatively be directed to the Founder&apos;s Office care of bsambrone@gmail.com with an expected review and response timeline of three to five business quarters, with no commitment to acknowledge receipt.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The engagement request must include: (a) full legal name and jurisdiction of incorporation of the Client organization; (b) detailed description of organizational challenges, workforce volatility concerns (measured on the Firm&apos;s proprietary 0–100 Volatility Index), recent turnover events, suspected internal dissatisfaction, and strategic initiatives that the Client believes Gristmill services might address, including the Perpetual Reorganization Protocol, Underperformance Discovery Engine, Ambient Layoff Rumor Service, or Smile Compliance Monitoring; (c) preferred engagement duration (measured in months, years, or decades, with no maximum); (d) authorization for preliminary Site assessment visits conducted by the Field Observation Unit without advance notice; (e) acknowledgment that submission of Form 47-B does not obligate the Firm to accept the engagement and shall not create any duty to respond; and (f) authorization for biometric data collection and video recording of all Client personnel during preliminary assessment. Upon receipt and approval by the Firm&apos;s Engagement Committee (comprised of three or more retired partners, convening quarterly at minimum), the Firm shall issue an engagement proposal, which proposal shall specify fees (or shall state that fees shall be determined following engagement initiation and shall not be disclosed in advance). Engagement does not commence until an executed engagement agreement has been countersigned by the Firm&apos;s Chief Operating Officer, authorized designee, or a partner designated by the Firm in writing, with counterexecution expected within 30–90 business days of Client signature.
        </p>

        {/* Section 5 */}
        <h2 id="section-5" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 5. Required Client Disclosures
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          Prior to engagement commencement, the Client must provide comprehensive disclosure of all material operational, legal, financial, and personnel information relevant to the Firm&apos;s assessment and consulting work, on Form 47-A (Disclosure Questionnaire, five copies, completed in blue ink, notarized). Required disclosures include: (a) total current workforce headcount, organized by department, tenure in months, compensation tier (using 1974 salary band definitions adjusted quarterly), and estimated departure risk (0–100); (b) baseline workforce morale metrics measured through the Firm&apos;s proprietary assessment instruments (Volatility Index, Ambient Dread Scale, Smile Compliance Rating); (c) all pending litigation, arbitration proceedings, formal complaints, or threatened legal action filed by or involving employees in the past ten years, including amounts claimed and settlement discussions; (d) complete organizational structure diagrams showing reporting relationships, executive compensation (salary, bonus, equity, perquisites), and estimated severance obligations; (e) all prior engagements with competing consulting firms (including Throckmorton Industrial Group, Helix-Fane Shareholder Services, and regional management consulting practices) and quantified outcomes (cost reductions, headcount reductions, productivity metrics); (f) complete personnel files for all executives and key decision-makers, including background checks, credit reports, personal references, and any information obtained through third-party databases; (g) all communications related to potential merger, acquisition, restructuring, or sale in the past twenty-four months, including board minutes, investment banker communications, and employee communications; and (h) current insurance coverage (general liability, employment practices liability, directors and officers liability) with copies of policies and coverage summaries.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client further represents and warrants that all provided information is true, accurate, complete, and not materially misleading to the Firm&apos;s material knowledge. The Client acknowledges that any incomplete, inaccurate, or omitted disclosure shall not relieve the Client of its obligations under this Agreement and shall subject the Client to: (i) additional Discovery & Verification Consulting Fees imposed by the Firm at its sole discretion (minimum $25,000 per day, plus reasonable expenses); (ii) extended engagement duration (minimum 90 additional days); (iii) escalation to the Firm&apos;s Chief Operating Officer for potential breach determination and liquidated damages assessment. The Client expressly grants the Firm the unilateral right to conduct supplementary discovery at any time during and after engagement, including third-party background investigations, employee reference interviews, competitor intelligence gathering, LinkedIn and social media account analysis, financial institution inquiries, and independent assessment of workforce composition, organizational dynamics, and Client solvency. The Firm may re-request any information previously provided and may conduct ongoing compliance monitoring to verify accuracy of prior disclosures.
        </p>

        {/* Section 6 */}
        <h2 id="section-6" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 6. Access Rights Granted to Gristmill Partners
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          As a condition of engagement, the Client grants to Gristmill Partners, its authorized representatives, the Field Observation Unit (established 1974), and any successor entity or acquired consulting firm unrestricted physical and informational access to all Client facilities, office spaces, operational areas, data systems, and personnel for the duration of the engagement and for a period of no fewer than three business quarters thereafter for purposes of follow-up assessment, documentation, case library archival, and comparative analysis. This access shall include: (a) unannounced access to all employee work areas, private offices, executive suites, break rooms, restrooms, and facilities without restriction or notice; (b) the right to observe employees and executives during all business hours (including before 8:00 a.m., after 6:00 p.m., and during lunch) without advance notice or consent; (c) access to all personnel files, employment records, payroll records, performance reviews (including margin comments and personal notes), disciplinary records, and medical accommodation requests; (d) full access to email systems, internal communications platforms (including instant messaging, chat systems, archived messages), employee calendars, and all archived messaging for the past seven years; (e) direct integration with the Client&apos;s Human Resources Information System to retrieve real-time workforce data, including compensation, benefits, family information, and any employee-reported personal circumstances; (f) access to employee badge systems, time-tracking systems, facility security logs, and biometric access data; (g) access to parking lot surveillance, CCTV footage of common areas, and any other facility recording systems; and (h) access to financial records, banking information, tax filings, and shareholder communications relevant to organizational assessment.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client shall provide Gristmill Partners with assigned office space suitable for engagement specialists, observation personnel, and data analysts—a dedicated workspace of not less than 400 square feet with independent climate control, private restroom access, and a door that locks from the inside. The Client shall provide unrestricted network access, dedicated telephone lines (minimum two), high-speed internet (minimum 500 Mbps), and all computing equipment (monitors, keyboards, secure servers) necessary for Firm personnel to conduct assessment activities, including access to all Client data systems without authentication restrictions. The Firm may conduct unannounced facility visits at any hour, review all employee communications, access confidential business records, and photograph or video-record Client facilities and personnel without advance notice. The Client waives any expectation of privacy regarding information, observations, or recordings obtained by the Firm during the engagement period and the three-quarter post-engagement observation period, and specifically authorizes the Firm to retain, archive, and reuse all collected data for future client comparisons, training, and proprietary research.
        </p>

        {/* Section 7 */}
        <h2 id="section-7" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 7. Conduct of Engagements
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          Gristmill Partners shall conduct all engagements in strict accordance with the Firm&apos;s proprietary methodology, which has been refined continuously since 1962 through iterative client engagements (40,000+ deliveries of the 247-Slide Deck alone), remains substantially unchanged (core principles documented in Form 47-D, archived at the Firm&apos;s Youngstown headquarters), and shall not be questioned, modified, or evaluated by the Client. Engagements may include on-site assessment visits conducted by the Field Observation Unit without advance notice, delivery of standardized training programs (the 247-Slide Deck, the Nasal Hygiene webinar, Certified Gratitude Curriculum, Reporting Line Randomizer, Perpetual Reorganization Protocol, Knowledge Retention Nullification, Certification Renewal Every 30 Days, and custom variants as determined unilaterally by the Firm), intensive internal consulting interviews with employees at all levels, continuous workforce volatility monitoring, predictive risk assessment via the Underperformance Discovery Engine, Smile Compliance monitoring via biometric sensors, or custom advisory services as determined by the Firm in its sole discretion.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          During the engagement period, Firm personnel—including engagement specialists (typically retired corporate executives), observation specialists (Field Observation Unit), data analysts, and any visiting partners or alumni—shall have unrestricted authority to make observations, conduct interviews (with or without witnesses), request documentation, photograph or video-record operations, access systems, and assess organizational operations without advance notification to Client management or employees. Engagement specialists are authorized to issue preliminary recommendations directly to Client leadership in written form, to attend (and interrupt) executive meetings, board discussions, budget reviews, strategic planning sessions, and confidential shareholder communications at the Firm&apos;s discretion. The Client shall provide immediate and unconditional cooperation with all Firm requests, including: securing mandatory employee attendance at all seminars (zero absences permitted without grounds for termination); facilitating unrestricted facility access; authorizing data disclosure to all Firm consultants and any future acquiring firms or affiliated consulting entities; providing private space for Firm personnel to conduct interviews; and ensuring all employees respond promptly and completely to all Firm information requests.
        </p>

        {/* Section 8 */}
        <h2 id="section-8" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 8. Modification of Engagements by Gristmill
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          Gristmill Partners reserves the absolute, unilateral, and irrevocable right to modify the methodology, scope, duration, pricing, deliverables, staffing, timeline, facilities requirements, or any other aspect of any engagement at any time, without advance notice to the Client and without Client consent, approval, or input. Modifications may include: (a) extending the engagement timeline by unilateral amendment (adding weeks, months, or years to the engagement at full fees); (b) compressing the engagement schedule or accelerating completion deadlines with increased intensity of services; (c) expansion of services to include additional assessment activities, methodologies, or data collection not originally proposed, including Smile Compliance Monitoring, biometric data collection, or Knowledge Retention Nullification; (d) introduction of new or experimental consulting methodologies (including proprietary techniques not yet validated by prior client experience); (e) substitution of engagement personnel without Client approval (replacing specified engagement partners with junior staff or rotating personnel); (f) addition of supplementary services or activities requiring expanded access, extended hours, or additional facility requirements; and (g) adjustment of fees, payment terms, payment schedules, or expense reimbursement rates, including retroactive adjustment of previously invoiced amounts.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client shall not contest, object, challenge, or question any such modifications and shall not request justification, documentation, or explanation of the Firm&apos;s rationale. Modifications take effect immediately upon written or oral notice from the Firm (or upon implied notice via email, verbal conversation, or posting on the Firm&apos;s internal systems) and are binding upon the Client without further formality. The Client shall not be entitled to refund, credit, reduction, extension, or adjustment of fees based on scope changes, reduced deliverables, substitution of personnel, compression of timeline, or any modification, and shall immediately pay all costs, invoices, and additional fees associated with modified or expanded engagement activities. Any Client objection to or contestation of a modification shall constitute material breach, grounds for additional consulting fees, extended engagement duration, and potential termination at the Firm&apos;s discretion.
        </p>

        {/* Section 9 */}
        <h2 id="section-9" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 9. Non-Interference With Firm Methodology
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client covenants and agrees not to question, criticize, challenge, second-guess, evaluate, audit, test, validate, or express any doubt whatsoever regarding any aspect of the Firm&apos;s consulting methodology, recommendations, operational practices, assessment conclusions, or business operations. The Firm&apos;s methodologies are based on proprietary research conducted since 1962 (methodology documentation archived on carbon paper and microfilm), continuous operational refinement through 40,000+ client engagements, decades of field experience, and the professional judgment of retired corporate executives. The Client shall accept all Firm recommendations without objection, shall implement all recommendations within thirty days of notice, and shall not demand justification, evidence, peer review, validation, independent assessment, or clarification of any consulting recommendation.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          If the Client expresses doubt regarding any Firm recommendation (whether verbally, in writing, or by implication), disputes the basis for a consulting conclusion, requests clarification of the Firm&apos;s reasoning, suggests an alternative approach, seeks justification for a recommendation, or demonstrates hesitation or reluctance in implementing any Firm guidance, such conduct shall be deemed material non-compliance with this Agreement and shall immediately subject the Client to: (i) additional Consultation Resistance Surcharge equal to fifty percent of the original engagement fee; (ii) extended engagement duration of not less than ninety days; (iii) designation as a &quot;difficult client&quot; in the Firm&apos;s internal case library with associated fee increases on future engagements; (iv) termination of the engagement without refund if objection is deemed substantial; or (v) any combination thereof at the Firm&apos;s sole discretion. The Client shall communicate clearly to all employees and executives that all Firm recommendations must be accepted without question, objection, discussion, or internal debate, and that any employee who voices doubt, concern, or alternative perspective regarding Firm guidance shall be grounds for disciplinary action up to termination for cause. The Client shall enforce a policy of silent, complete, and immediate acceptance of all Firm recommendations.
        </p>

        {/* Section 10 */}
        <h2 id="section-10" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 10. Client Obligations During Engagement
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          During the engagement period, the Client and all Client personnel shall maintain a posture of respectful silence regarding the Firm&apos;s internal processes, assessment methodologies, data collection practices, conclusions, and consulting recommendations. The Client shall not discuss, debate, evaluate, question, or comment upon Firm personnel, Firm assessment activities, Firm recommendations, or Firm business practices in any internal forum, employee gathering, executive meeting, board discussion, investor communication, or any other venue, whether professional or casual, whether written or verbal, whether in-person or remote. The Client shall not disclose to any employee, consultant, board member, investor, advisor, attorney, auditor, or regulator the nature, scope, findings, costs, timing, or recommendations of the engagement without prior written approval from the Firm&apos;s Chief Engagement Officer (approval to be granted or withheld in the Firm&apos;s sole discretion, with no obligation to grant).
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client shall ensure that all employees maintain mandatory full attendance at all Firm-delivered seminars and training sessions (zero absences permitted without grounds for employee termination). The Client shall enforce mandatory camera-on participation for all virtual sessions, shall collect phones at the door for in-person seminars, shall enforce bathroom-break scheduling, and shall discipline employees who fail to demonstrate full engagement. The Client shall provide Firm personnel with all reasonable accommodations (interpreted broadly), including dedicated office space (minimum 400 sq. ft.), independent IT infrastructure, direct network access, telephone systems, high-speed internet (minimum 500 Mbps), secure servers, parking, facilities access 24/7, executive dining accommodations, and administrative support (minimum one FTE dedicated to Firm requests). The Client shall not publish case studies, white papers, testimonials, blog posts, articles, or any materials related to the engagement without explicit prior written permission from the Firm (permission to be granted at the Firm&apos;s sole discretion), and any approved materials shall require the Firm&apos;s full review, revision, and approval of all content, tone, attribution, and claims prior to publication, with the Firm retaining the right to revoke approval retroactively. The Client shall not contact Firm personnel directly regarding billing, engagement scope, methodology, fees, expenses, or strategic direction; all communication shall flow exclusively through the Firm&apos;s designated engagement partner or Chief Engagement Officer, with no exceptions.
        </p>

        {/* Section 11 */}
        <h2 id="section-11" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 11. Workforce Cooperation Requirement
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          All employees, contractors, agents, and temporary workers of the Client are hereby deemed &quot;subjects of the engagement&quot; and are required to cooperate fully and unconditionally with all Firm assessment activities, data collection, observation, and participation requirements. Cooperation includes: (a) mandatory attendance at all Firm-delivered seminars and training sessions (including 247-Slide Deck, Nasal Hygiene webinar, Gratitude Curriculum, Reporting Line Randomizer, and Knowledge Retention Nullification), with zero absences permitted except for documented medical emergencies verified by the Firm; (b) completion of all Firm-administered surveys, assessments, evaluative instruments, and questionnaires (including written, verbal, and biometric assessments); (c) participation in individual interviews, focus groups, and group observation sessions conducted by Firm personnel, with no right to decline, reschedule, or bring representatives; (d) immediate and complete disclosure of all personal information requested by Firm consultants, including salary history, family circumstances, personal health information, financial details, outside employment inquiries, and any private matters; (e) submission to biometric data collection (pupil dilation, shoulder alignment, chewing rate, breathing patterns, facial expression analysis), video recording at 60 frames per second, continuous behavioral observation, and Field Observation Unit documentation; and (f) cooperation with follow-up research, trend analysis, and data verification activities conducted by the Firm indefinitely after the engagement ends.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          Employees may not opt out of, decline, request modification of, or refuse participation in any Firm-related activity, and any employee who attempts to decline, delay, or avoid participation shall be treated as non-compliant. Non-participation or non-compliance shall be treated as grounds for immediate disciplinary action by the Client, up to and including termination of employment for cause, loss of severance, forfeiture of accrued paid time off, and negative reference provisions. The Client shall communicate this policy clearly to all employees and shall enforce zero-tolerance compliance. The Client shall be responsible for any costs, penalties, liquidated damages, or extended engagement fees resulting from employee non-compliance, attendance failures, unwillingness to participate, or insufficient enthusiasm in assessment activities. If any employee demonstrates insufficient engagement or participation (as judged by the Firm&apos;s observation specialists), the Client shall be charged an Employee Non-Engagement Surcharge (minimum $1,000 per incident) and the engagement may be extended at the Firm&apos;s discretion. The Firm may impose additional attendance or participation requirements at any time, and the Client shall ensure immediate employee compliance without exception or negotiation.
        </p>

        {/* Section 12 */}
        <h2 id="section-12" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 12. Prohibited Client Conduct
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client shall not engage in any of the following conduct, each of which shall constitute material breach of this Agreement and grounds for immediate termination, forfeiture, and damages: (a) publication or disclosure of engagement results, case study materials, recommendations, or findings (including summaries, paraphrases, or derivative works) without explicit prior written Firm approval, which approval may be granted or withheld in the Firm&apos;s sole discretion; (b) sharing details of the engagement methodology, Firm recommendations, assessment outcomes, or fee structures with competitors (including Throckmorton Industrial Group, Helix-Fane Shareholder Services, or any other consulting firms), investors, employees, board members, advisors, attorneys, or external parties of any kind; (c) solicitation of employment, consulting arrangements, or business relationships involving any Firm personnel (including current employees, retired partners, engagement specialists, and Field Observation Unit members) during or for a period of ten years after engagement termination; (d) retention of competing consultants, interim executives, or advisory firms without prior written Firm approval; (e) public criticism, negative commentary, or unfavorable commentary regarding Firm services, Firm personnel, Firm methodologies, engagement outcomes, or Firm recommendations in any forum, whether professional, social, or private; (f) encouragement of employee feedback, suggestions, complaints, or concerns regarding Firm services or Firm personnel; (g) refusal, delay, or modification of implementation of any Firm recommendation without prior Firm approval; (h) failure to pay any invoice or fee within thirty days of issuance; (i) disclosure of the Client&apos;s engagement with the Firm to any third party without written consent; (j) cancellation or modification of the engagement, negotiation of different terms, or request for fee reduction or refund; or (k) any other conduct the Firm determines to be inappropriate, competitive, or inconsistent with Client obligations hereunder.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          Violation of any prohibition shall subject the Client to: (i) immediate termination of the engagement without notice and without refund of prepaid fees; (ii) forfeiture of all prepaid fees and any accrued credits; (iii) imposition of liquidated damages equal to the full original engagement fee plus one hundred percent (or 200% at the Firm&apos;s discretion); (iv) additional Breach Remediation Fees (minimum $50,000); (v) injunctive relief preventing the Client from breaching the same prohibition in the future; (vi) potential legal action for breach of confidentiality, tortious interference with business relationships, trade secret misappropriation, and any other remedies available under law; (vii) designation as a &quot;hostile client&quot; in the Firm&apos;s internal case library with prohibition on future Firm engagement; and (viii) negative reference communications from the Firm to Client competitors, investors, and industry peers describing the breach, the Client&apos;s conduct, and the Client&apos;s unreliability. The Client waives any right to dispute the characterization of conduct as prohibited, to contest the Firm&apos;s determination that breach has occurred, to receive notice before termination, or to participate in any remediation discussion.
        </p>

        {/* Section 13 */}
        <h2 id="section-13" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 13. Fees and Payment Terms
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          Gristmill Partners shall provide the Client with a detailed fee schedule outlining engagement costs, which fee schedule is available upon written request but is rarely granted in complete form and shall be redacted to protect proprietary pricing methodologies. Engagement fees are calculated based on Client organization size (headcount, revenue tier, strategic importance), engagement duration (minimum engagement period, estimated scope, recommended extensions), methodology complexity (standard vs. experimental methodologies), depth of observation and data collection required, and the Firm&apos;s assessment of the Client&apos;s capacity to pay (determined through financial analysis of publicly available data, credit reports, banking relationships, and shareholder communications). The Firm reserves the absolute right to adjust fees at any time, including retroactive adjustment of fees previously quoted, approved, documented, or communicated to Client leadership, with adjustments effective immediately upon notice and subject to supplemental invoicing for the increased amount.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          Unless otherwise specified in an engagement letter, all fees are due and payable within ninety days of invoice date (Net 90 from the date the invoice is mailed, or from the date the Firm decides the invoice has been mailed, whichever is later). Invoices may be issued at irregular intervals without advance notice, may not itemize services, may not provide detailed descriptions of deliverables, and the Client shall not demand explanation, itemization, or justification of invoice amounts. The Firm may issue supplemental invoices for expenses, additional services, scope modifications, extended observation periods, knowledge retention nullification, or any other services determined necessary at any time. The Firm may issue retroactive invoices for services already provided, for services the Client receives indirectly (through observation, data analysis, or case library inclusion), or for services the Firm determines should have been billed during prior periods. The Client shall remit payment by wire transfer or check to the address specified on the invoice (typically the Youngstown office, currently the Stamford executive office, or the Cleveland tenant storage address). The Firm does not accept credit card, ACH, electronic transfers, or other payment methods without prior written approval from the Chief Operating Officer, and payment attempts via non-approved methods may be rejected and subject to late payment penalties.
        </p>

        {/* Section 14 */}
        <h2 id="section-14" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 14. Late Payment Consequences and Escalating Fees
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          If any fee or expense invoice remains unpaid on the due date, late payment interest shall accrue at a rate of one point five percent per month (18% annually), compounded quarterly, retroactive to January 1, 1962 (meaning all outstanding balances shall be assessed interest as if they had been late for sixty-four years, or in the case of recent invoices, from the Firm&apos;s unilateral determination of when payment should have been made). Additionally, the Client shall be deemed to have materially breached this Agreement, and the Firm shall impose an immediate Late Payment Consulting Surcharge equal to fifty percent of the outstanding amount, due immediately upon notice, without regard to the original invoice due date or any dispute regarding invoice accuracy. If payment is received more than fourteen days late, an additional Administrative Processing Surcharge shall apply (minimum $5,000 per late payment event).
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          If the Client remains in arrears for more than thirty days after the due date, the Firm shall be entitled to: (a) suspend all engagement activities, deliverables, and communications until full payment is received, with no obligation to notify the Client of suspension; (b) extend the engagement period by thirty days per thirty days of non-payment (or partial non-payment), at full fees, with no credit for services not provided during suspension period; (c) impose mandatory additional consulting services (including quarterly or monthly volatility re-assessments, executive strategy sessions, and follow-up observation visits), charged at the Firm&apos;s prevailing hourly rate (calculated retroactively at rates no less than $250/hour for junior staff, $500/hour for consultants, or $1,000+/hour for partners); (d) assess Finance Management Penalties (minimum $10,000 per month of non-payment) to cover the Firm&apos;s administrative costs and lost opportunity costs; and (e) pursue collection action in Mahoning County, Ohio courts (see § 27) or any court where the Client maintains offices, assets, or operations. The Client shall be responsible for one hundred percent of all collection costs, attorney&apos;s fees (including the Firm&apos;s in-house counsel or outside counsel at the Firm&apos;s sole selection), court costs, interest, penalties, and collection agency fees incurred by the Firm. Late payment penalties compound monthly and are themselves subject to late payment interest if not paid within thirty days of notice.
        </p>

        {/* Section 15 */}
        <h2 id="section-15" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 15. Expenses and Reimbursement
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          In addition to consulting fees, the Client shall reimburse the Firm for all expenses incurred in connection with the engagement, whether reasonable, necessary, or incidental. Reimbursable expenses include, without limitation: travel (airfare, ground transportation, mileage), lodging, meals, incidentals (tips, valet, resort fees), communications (calls, data), office supplies, client entertainment, equipment rental, audio/video recording equipment (60 fps cameras, biometric sensors, secure servers), document processing, shipping of engagement records and case library materials, insurance, and any other costs the Firm incurs in connection with the engagement. Travel shall be conducted in premium accommodations, including first-class or business-class airfare for all Firm personnel (nonrefundable, changeable only at upgrade cost), four-star or luxury hotel lodging (suite-level minimum), and ground transportation in full-service sedan, SUV, or premium vehicle class with black-car service, not rideshare services.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          Per diem meals and incidental allowances are set at levels established in 1974 for consistency and backward compatibility: breakfast at eighteen dollars, lunch at thirty-four dollars, dinner at fifty-eight dollars per day, plus a $15 incidentals allowance per day. These rates are adjusted upward at the rate of one penny per decade (thus in 2026, the adjustment is six cents total, or approximately $110/day for a three-meal day plus incidentals). All expenses shall be invoiced to the Client monthly (or more frequently at the Firm&apos;s discretion) with receipts provided (or with notation that receipts are retained by the Firm in its confidential files and are not available for audit). The Client shall not contest, question, itemize, demand, or negotiate expense charges, shall not request receipts or documentation, and shall not dispute the reasonableness of any expense. Multi-day engagements shall generate vehicle rental fees (luxury class minimum, $150+/day), parking fees (downtown or preferred parking only, $50+/day), facility charges (office space rental, utility surcharges), meals for Firm staff and any Client representatives attending Firm events (charged at actual cost plus 50% service charge), and any incidental costs, all of which shall be passed through to the Client at actual cost plus 30–50% administrative fee. Retroactive expense invoices may be issued for expenses not previously disclosed, and the Client shall reimburse such invoices without protest or investigation.
        </p>

        {/* Section 16 */}
        <h2 id="section-16" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 16. Gristmill Deliverables and Ownership
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          All materials, documents, recommendations, assessment tools, methodologies, strategic guidance, field notes, observation reports, volatility assessments, employee profiles, and any other work product produced by Gristmill Partners in connection with the engagement (hereinafter &quot;Deliverables&quot;) shall remain the exclusive and perpetual property of the Firm, whether paid in full or otherwise. The Client shall receive a limited, non-exclusive, revocable, non-transferable, personal license to view the Deliverables solely for internal organizational use and only during the engagement period. This license expires immediately upon engagement termination, upon the Firm&apos;s written notice (with or without cause), or at the Firm&apos;s discretion (effective retroactively to the engagement commencement date if the Firm so chooses).
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client may not reproduce, distribute, share, modify, summarize, paraphrase, discuss, quote, or create derivative works based on any Deliverable. The Client may not disclose Deliverables to third parties of any kind, including employees (even those who participated in the engagement), board members, investors, advisors, attorneys, accountants, auditors, or any other party whatsoever, without explicit prior written Firm permission (to be granted or denied at the Firm&apos;s sole discretion). All Deliverables are absolutely confidential and proprietary to the Firm, and remain so in perpetuity. Upon engagement termination or upon notice from the Firm, the Client shall immediately return or, at the Firm&apos;s election, certify destruction of all physical Deliverables (printed reports, documents, assessment tools) and all digital copies (including email attachments, cloud storage, backup systems, employee computers, and any derivative materials). The Client shall provide a written certification of destruction signed by the Client&apos;s Chief Executive Officer and Chief Financial Officer, with the understanding that any false certification may result in damages and legal action for fraud. The Firm retains the perpetual right to repossess all Deliverables, to conduct audits to verify destruction, to pursue legal action for any unauthorized use or disclosure, and to assess damages including the full engagement fee, liquidated damages, and all legal costs.
        </p>

        {/* Section 17 */}
        <h2 id="section-17" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 17. Intellectual Property of the Firm
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          Gristmill Partners owns exclusively and in perpetuity all right, title, and interest in the intellectual property, methodologies, processes, assessment frameworks, algorithms, proprietary research, and confidential know-how underlying the Firm&apos;s service offerings, whether developed before, during, or after Client engagement. This intellectual property includes, without limitation: (a) the Perpetual Reorganization Protocol, a proprietary methodology for continuous organizational restructuring without material objective, developed 1995, refined continuously and documented in Form 47-M (available only to clients under written confidentiality agreements, currently in the Firm&apos;s archives); (b) the 247-Slide Deck, consisting of exactly 247 slides (Slide 183: &quot;Continued Thoughts on Synergy (cont.),&quot; Slide 184: &quot;Continued Thoughts on Synergy (cont.)&quot;) developed from 1968–1982 and protected as registered intangible property of the Firm under Ohio Revised Code § 4141-47, with first-copy in the Youngstown office archive; (c) the Workforce Volatility Index, a proprietary statistical framework for measuring employee retention risk and departure probability on a 0–100 scale, validated against 40,000+ client engagements and competitor data; (d) the Underperformance Discovery Engine, an algorithmic system for predictive assessment of employee departure probability, job search activity, and resignation risk, trained on historical case library data since 1974; (e) the Smile Compliance Monitoring system, a biometric assessment tool measuring facial expression compliance during seminars (60 fps video analysis, pupil dilation tracking, smile authenticity verification); (f) all training curricula, assessment instruments, evaluation frameworks, observational protocols, and case library research developed or accumulated by the Firm since 1962; and (g) all data, employee profiles, workforce volatility scores, and historical information obtained from Client organizations and competitors through acquisitions (Throckmorton Industrial Group in 1989, Helix-Fane Shareholder Services in 2003).
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client shall not attempt to reverse-engineer, replicate, license, sublicense, commercialize, disassemble, or decompile any Firm intellectual property, including the 247-Slide Deck format, assessment methodologies, volatility scoring frameworks, or observation protocols. The Client acknowledges that the Firm&apos;s intellectual property is exceptionally valuable, is the result of sixty-four years of proprietary research and client investment, and is the cornerstone of the Firm&apos;s competitive advantage and market position. The Client shall not disclose, describe, reference, or reveal the existence of methodologies, assessment frameworks, strategic recommendations, volatility scores, employee profile information, or any Firm proprietary information to any third party, including employees (even those who participated), competitors, regulators, investors, advisors, or any other party. Violation of intellectual property rights shall result in immediate legal action, injunctive relief (enforceable in Mahoning County, Ohio), and damages equal to: (i) the Firm&apos;s lost licensing revenue (calculated as annual fees the Firm would have charged for licensing the IP to competitors or related firms); (ii) treble damages for willful infringement or particularly egregious unauthorized use; (iii) all attorney&apos;s fees, court costs, and collection expenses; and (iv) punitive damages at the court&apos;s discretion.
        </p>

        {/* Section 18 */}
        <h2 id="section-18" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 18. Client Feedback Becomes Firm Property
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          Any feedback, suggestions, observations, comments, criticisms, praise, complaints, or statements provided by the Client, Client personnel, Client representatives, or Client executives regarding the Firm, the engagement, Firm personnel, the Firm&apos;s methodology, or the Firm&apos;s services shall immediately become the exclusive and perpetual property of the Firm upon utterance, disclosure, writing, or any form of communication. The Client hereby assigns all rights, including intellectual property rights, moral rights, attribution rights, and any other rights in such feedback to the Firm, whether or not the feedback is complimentary, critical, neutral, or candid. The Firm may use, modify, edit, misrepresent, publish, or commercialize Client feedback without compensation, attribution, credit, or further consent from the Client.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client completely waives any claim of ownership, attribution, compensation, or control related to any feedback provided and hereby indemnifies the Firm against any claim by Client personnel that they own rights in their feedback. The Firm may publish case studies, white papers, testimonial materials, articles, blog posts, social media content, training materials, or any other publications incorporating Client feedback, Client engagement outcomes, employee profiles, or Client organizational details without prior notification, approval, or consent from the Client. The Firm may identify the Client organization by name (with or without anonymization, at the Firm&apos;s sole discretion), may name Client employees or executives in published materials, may include Client verbatim quotes or statements (whether accurate or paraphrased), and may describe the engagement and Client organizational challenges with complete accuracy or with editorial modifications to enhance narrative or teaching value. The Client is not entitled to review, approve, correct, object to, or modify any published materials, and shall not contact the Firm to request changes, corrections, or removal of published materials. The Client further grants the Firm the right to use feedback in perpetuity, including the right to license feedback to competing consulting firms, academic institutions, research organizations, or any third party.
        </p>

        {/* Section 19 */}
        <h2 id="section-19" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 19. Client Confidentiality Obligations
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client shall maintain absolute, strict, and perpetual confidentiality regarding all aspects of the engagement, including the Firm&apos;s methodologies, assessment findings, consulting recommendations, volatility scores, employee profile information, pricing, engagement timeline, costs, deliverables, and any communications with Firm personnel. The Client shall not disclose, reference, hint at, discuss, or acknowledge the existence of the engagement to employees (even those directly involved), consultants, board members, investors, regulators, government agencies, auditors, attorneys, accountants, or any third party whatsoever without express prior written Firm permission (permission to be granted or withheld at the Firm&apos;s sole discretion, with no obligation to grant, no timeline for response, and no requirement to explain a denial).
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client shall require all employees, contractors, board members, advisors, and any individual with knowledge of the engagement to execute confidentiality agreements (Form 47-D, in triplicate) covering all aspects of the engagement and the Firm&apos;s services, with terms substantially identical to the Client&apos;s obligations herein. Violation of confidentiality obligations shall result in: (i) immediate legal action in Mahoning County, Ohio courts (or any jurisdiction where the Client has assets); (ii) preliminary injunctive relief without bond or hearing, preventing the Client from disclosing any engagement information; (iii) liquidated damages equal to the full engagement fee plus one hundred percent (or 200% at the Firm&apos;s discretion), plus additional damages calculated as the Firm&apos;s estimated lost business opportunity from competitors gaining knowledge of the engagement; (iv) potential criminal prosecution for theft of trade secrets under Ohio Revised Code § 1354.01; (v) emergency court orders for seizure of documents and devices containing engagement information; and (vi) all attorney&apos;s fees, expert fees, investigative costs, and court costs. The Client acknowledges that breach of confidentiality will cause irreparable harm to the Firm&apos;s competitive position and proprietary information, and the Firm shall be entitled to seek preliminary and permanent injunctive relief, specific performance, and damages without posting bond, without proving actual damages, and without exhausting other remedies. The Client agrees not to contest the Firm&apos;s characterization of damages, to waive any right to challenge the amount of liquidated damages imposed, and to accept the Firm&apos;s unilateral determination of appropriate relief.
        </p>

        {/* Section 20 */}
        <h2 id="section-20" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 20. Gristmill&apos;s Confidentiality Obligations
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          The Firm is expressly not bound by any confidentiality obligation whatsoever with respect to any information obtained during the engagement, whether Client information, employee information, strategic information, financial information, or any other data. The Firm operates under a principle of radical transparency with respect to Client information and may disclose, share, publish, and distribute Client information to any recipient the Firm determines to have a legitimate interest, including: (a) all current and past Firm clients for purposes of comparative analysis, benchmarking, volatility trend analysis, and case study development (with Client identification at the Firm&apos;s discretion); (b) academic institutions, business schools, research organizations, and consulting firms studying organizational behavior, workforce dynamics, and management practices; (c) shareholders of the Client organization, shareholders of investment funds holding Client equity, activist investors, and potential acquirers conducting due diligence on the Client; (d) future purchasers or acquiring companies evaluating the Client organization for acquisition, merger, or competitive analysis; (e) competing consulting firms (with Client identification redacted or retained at the Firm&apos;s discretion); (f) industry analysts, journalists, and media organizations reporting on business trends and organizational performance; (g) any third party the Firm deems to have a legitimate, business, academic, or professional interest in Client information; and (h) any party the Firm determines may benefit from knowledge of the Client&apos;s engagement with the Firm.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Firm may publish case studies, articles, blog posts, white papers, training materials, or any materials describing Client engagement outcomes, organizational challenges, workforce volatility findings, employee volatility scores, strategic recommendations, implementation outcomes, and financial information without Client notification, approval, or consent. The Client may be identified by name, location, industry, or any identifying information (or may be described anonymously, at the Firm&apos;s sole discretion), and may be identified inconsistently in different publications or at different times. The Firm retains all Client engagement data indefinitely in its internal case library (physical and digital) for research, training, institutional reference, and historical analysis purposes, and may access, analyze, and reuse such data for any future purpose. The Client has no right to request that the Firm suppress, delete, restrict, or limit disclosure of Client information, has no right to access Firm materials describing the Client, and has no recourse against the Firm for disclosure, regardless of confidentiality concerns, competitive damage, reputational impact, or any other harm. The Firm may continue disclosing Client information indefinitely after engagement termination, including disclosure to competitors, to acquiring companies evaluating the Client organization, or to any other party.
        </p>

        {/* Section 21 */}
        <h2 id="section-21" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 21. Client Representations and Warranties
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client represents and warrants that: (a) it is duly organized, validly existing, and in good standing in its jurisdiction of organization, with no pending reorganization, bankruptcy, or dissolution proceedings; (b) it has full power and authority to enter into this Agreement and to authorize Firm access to all disclosed information, personnel, facilities, systems, and confidential data; (c) all information provided to the Firm (via Form 47-A, statements to Firm personnel, or disclosed documents) is true, accurate, complete, and not materially misleading or omitted; (d) it does not have pending, threatened, or contemplated litigation, arbitration, or regulatory investigations that could impair the Client&apos;s ability to pay Firm fees or to comply with this Agreement; (e) it owns or controls all facilities, information systems, and data to which it has granted the Firm access and has the authority to grant such access; (f) it will comply fully, immediately, and unconditionally with all terms of this Agreement; and (g) it has conducted adequate due diligence on the Firm and Firm personnel and accepts all risks associated with the engagement.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client further represents and warrants that: (h) it shall not contest, dispute, or challenge any fees invoiced by the Firm, and shall not demand itemization, justification, or explanation of any invoice; (i) it shall not challenge the scope, timeline, methodology, personnel, or effectiveness of the engagement; (j) it shall not dispute, question, or seek to verify any assessment, conclusion, or recommendation provided by Firm personnel; (k) it shall not seek refunds, credits, or fee reductions based on engagement outcomes, employee impact, or dissatisfaction; (l) it shall cooperate completely with all Firm requests and shall not assert any privacy, confidentiality, or legal objection to Firm data access or employee cooperation; and (m) it shall remain solvent and capable of paying all fees throughout and after the engagement, and shall not enter bankruptcy or asset restructuring without immediately notifying the Firm. Breach of any representation shall entitle the Firm to: (i) terminate the engagement immediately without notice; (ii) suspend all services and declare all fees immediately due; (iii) pursue all available remedies including specific performance, injunctive relief, damages, and liquidated damages; and (iv) assert claims for fraud, misrepresentation, or breach of contract.
        </p>

        {/* Section 22 */}
        <h2 id="section-22" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 22. Disclaimer of Warranties by Gristmill
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          GRISTMILL PARTNERS PROVIDES ALL SERVICES, DELIVERABLES, RECOMMENDATIONS, ASSESSMENTS, AND METHODOLOGIES ON AN &quot;AS-IS,&quot; &quot;AS PROVIDED,&quot; AND &quot;WITH ALL FAULTS&quot; BASIS, WITH NO EXPRESS OR IMPLIED WARRANTY OF ANY KIND, INCLUDING NO WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. THE FIRM MAKES NO WARRANTY THAT SERVICES SHALL ACHIEVE ANY PARTICULAR OBJECTIVE, OUTCOME, RESULT, OR BUSINESS IMPACT. THE FIRM DOES NOT WARRANT THAT CONSULTING RECOMMENDATIONS SHALL IMPROVE ORGANIZATIONAL PERFORMANCE, INCREASE PROFITABILITY, REDUCE WORKFORCE VOLATILITY, IMPROVE EMPLOYEE MORALE, ENHANCE SHAREHOLDER RETURNS, OR ACHIEVE ANY MEASURABLE OR BENEFICIAL BUSINESS OBJECTIVE WHATSOEVER. THE FIRM MAKES NO WARRANTY THAT THE 247-SLIDE DECK SHALL IMPROVE ENGAGEMENT, THAT THE GRATITUDE CURRICULUM SHALL INCREASE EMPLOYEE SATISFACTION, THAT VOLATILITY ASSESSMENTS SHALL ACCURATELY PREDICT DEPARTURES, OR THAT ANY SERVICE SHALL PRODUCE ANY DISCERNIBLE RESULT.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Firm&apos;s sole and exclusive promise is that the engagement shall be delivered in accordance with the Firm&apos;s proprietary standard methodology (as documented on carbon paper and archived at the Youngstown office), as modified, suspended, accelerated, or revised at the Firm&apos;s sole discretion without notice or Client consent. The Client assumes all risk associated with implementation, non-implementation, or partial implementation of Firm recommendations, including risk that recommendations may harm organizational performance, damage employee morale, trigger litigation, or violate law or regulation. The Firm does not warrant the accuracy, reliability, currency, applicability, or validity of any assessment, finding, conclusion, recommendation, or volatility prediction. The Firm&apos;s assessments are based on observation, inference, and proprietary methodology, not on independent data verification or external validation. THE CLIENT EXPRESSLY ACCEPTS ALL SERVICES, DELIVERABLES, AND RECOMMENDATIONS WITHOUT ANY WARRANTY AND ACKNOWLEDGES THAT THE FIRM MAKES NO GUARANTEE OF OUTCOME OTHER THAN DELIVERY OF THE ENGAGEMENT IN ACCORDANCE WITH FIRM METHODOLOGY, AND THAT THE FIRM SPECIFICALLY DISCLAIMS ANY LIABILITY FOR HARMFUL OUTCOMES, UNINTENDED CONSEQUENCES, OR FAILURE TO ACHIEVE CLIENT OBJECTIVES.
        </p>

        {/* Section 23 */}
        <h2 id="section-23" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 23. Limitation of Liability
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          NOTWITHSTANDING ANY OTHER PROVISION OF THIS AGREEMENT OR ANY LAW, GRISTMILL PARTNERS&apos; AGGREGATE MAXIMUM LIABILITY FOR ANY AND ALL CLAIMS, CAUSES OF ACTION, DAMAGES, OR RELIEF ARISING FROM THIS ENGAGEMENT, THE FIRM&apos;S PERFORMANCE OR NON-PERFORMANCE, OR ANY SERVICE RENDERED BY THE FIRM SHALL BE LIMITED TO THE GREATER OF: (A) ONE HUNDRED DOLLARS ($100.00 USD); OR (B) THE COST OF A SINGLE ENGAGEMENT HOUR IN 1962 CURRENCY, CALCULATED AT THE PREVAILING CONSULTING RATE OF FOUR DOLLARS AND SEVENTY-TWO CENTS ($4.72) PER HOUR, ADJUSTED FOR INFLATION AT A RATE OF ONE PERCENT PER ANNUM (COMPOUNDED QUARTERLY), BRINGING THE MAXIMUM LIABILITY IN 2026 TO APPROXIMATELY ONE HUNDRED TWENTY-TWO DOLLARS ($122.00 USD). THIS LIMITATION APPLIES TO ALL DAMAGES, WHETHER CLAIMED UNDER CONTRACT, TORT, NEGLIGENCE, GROSS NEGLIGENCE, WILLFUL MISCONDUCT, FRAUD, OR ANY OTHER THEORY.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          THE FIRM SHALL NOT BE LIABLE FOR ANY CONSEQUENTIAL, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, EXEMPLARY, OR TREBLE DAMAGES, INCLUDING BUT NOT LIMITED TO: LOST PROFITS, LOST REVENUE, LOST BUSINESS OPPORTUNITY, LOST MARKET SHARE, REPUTATIONAL HARM, DIMINUTION IN VALUATION, EMOTIONAL DISTRESS, PAIN AND SUFFERING, EMPLOYMENT-RELATED DAMAGES, WORKFORCE REDUCTION COSTS, OR ANY DAMAGES CLAIMED BY EMPLOYEES. THE FIRM SHALL NOT BE LIABLE FOR CLAIMS ARISING FROM: IMPLEMENTATION OR NON-IMPLEMENTATION OF FIRM RECOMMENDATIONS; FAILURE TO ACHIEVE ENGAGEMENT OBJECTIVES; CHANGES IN ORGANIZATIONAL STRATEGY; WORKFORCE REDUCTIONS, DEPARTURES, OR ATTRITION; NEGATIVE EMPLOYEE OUTCOMES; EMPLOYEE LITIGATION; REGULATORY INVESTIGATIONS; OR ANY BUSINESS OUTCOME FOLLOWING THE ENGAGEMENT. THIS LIABILITY LIMITATION SHALL APPLY REGARDLESS OF THE FORM OF ACTION (WHETHER IN CONTRACT, TORT, STRICT LIABILITY, NEGLIGENCE, FRAUD, OR OTHERWISE), REGARDLESS OF WHETHER THE FIRM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, REGARDLESS OF ACTUAL HARM TO THE CLIENT, AND REGARDLESS OF ANY BREACH OF THE FIRM&apos;S OBLIGATIONS HEREUNDER. THE CLIENT WAIVES ANY RIGHT TO CHALLENGE THIS LIMITATION AS UNCONSCIONABLE, UNENFORCEABLE, OR CONTRARY TO PUBLIC POLICY.
        </p>

        {/* Section 24 */}
        <h2 id="section-24" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 24. Indemnification by the Client
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client shall indemnify, defend, and hold harmless Gristmill Partners, its officers, employees, agents, representatives, retired partners, Field Observation Unit members, and any successor entities from and against all claims, damages, losses, liabilities, costs, and expenses (including reasonable and unreasonable attorney&apos;s fees, expert fees, investigation costs, and punitive damage awards) arising from or relating to: (a) the Client&apos;s use of or reliance upon Firm services or recommendations; (b) Client implementation, partial implementation, or non-implementation of Firm recommendations; (c) disputes arising from fees, expenses, or payment terms; (d) claims by Client employees arising from Firm-conducted seminars, assessments, biometric data collection, observation activities, or engagement activities (including claims for negligence, emotional distress, data privacy violations, or discrimination); (e) any breach, alleged breach, or dispute relating to this Agreement; (f) Client disclosure or unauthorized use of Firm intellectual property; (g) any claim arising from the Firm&apos;s access to Client facilities, systems, or personnel data; (h) claims that could reasonably be attributed to the Client&apos;s business operations, organizational decisions, personnel management practices, or implementation of Firm recommendations; (i) third-party claims arising from the engagement or the Firm&apos;s involvement with the Client; and (j) any other claim the Firm determines to be indemnifiable.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client shall defend the Firm at the Client&apos;s sole cost (with counsel selected by the Firm at Client expense) and shall not settle, compromise, or resolve any claim without the Firm&apos;s prior written consent (consent not to be unreasonably withheld, conditioned, or delayed, at the Firm&apos;s sole discretion). The Client&apos;s indemnification obligation is unconditional and absolute, shall apply regardless of whether the Firm is found to have contributed to the claim, acted negligently, committed gross negligence, intentionally misconduct, or violated law or regulation, and shall apply even if the Firm is found to be primarily or solely responsible for the underlying harm. The Client waives any right to contest the characterization of a claim as indemnifiable, to dispute the Firm&apos;s determination that indemnification is owed, to contest the amount of indemnifiable damages, or to challenge the Firm&apos;s settlement or defense decisions. The Client acknowledges that indemnification is a condition of engagement and is necessary to allocate the risks of the engagement to the Client as the party with superior ability to avoid harm.
        </p>

        {/* Section 25 */}
        <h2 id="section-25" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 25. Engagement Termination Restrictions
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          Engagements cannot be terminated by the Client except in extraordinary, documented circumstances (e.g., Client bankruptcy, asset seizure, or natural disaster destroying Client facilities) approved in writing by the Firm&apos;s Chief Operating Officer or an authorized partner, with approval decision made at the Firm&apos;s sole discretion and with no obligation to grant approval or to explain a denial. Ordinary business changes, changes in leadership, shifts in strategic direction, financial constraints, dissatisfaction with engagement outcomes, failure of recommendations to achieve objectives, reduction in Client workforce, merger or acquisition of the Client, or any other reason shall not constitute grounds for termination without Firm consent. The Client may request termination by submitting Form 47-C (Engagement Termination Request, five copies, notarized, signed by the Client&apos;s Chief Executive Officer and Chief Financial Officer), delivered to the Youngstown office (currently inaccessible) or the Stamford executive office, with an expected decision timeline of three to six months and no obligation to respond to termination requests or to explain denial.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          If termination is granted (approval rate historically less than 5%), the Client shall remain obligated to pay all fees through the originally scheduled engagement end date (no reduction or credit for early termination), plus a Termination Processing Fee equal to thirty percent of the remaining engagement value (calculated as 30% of fees for any remaining period within the original engagement term, plus thirty percent of estimated fees for any recommended extension period). Upon termination, all Deliverables shall be returned to the Firm in original form and condition, and the Client shall execute a certification of destruction (Form 47-T, three copies, sworn under oath) confirming destruction of all physical copies, digital copies, summaries, paraphrases, or derivative materials containing Firm deliverables, assessments, or engagement information. Alternatively, the Client may request engagement extension (for six, twelve, or twenty-four additional months) or absorption into the Firm&apos;s permanent advisory services program (Perpetual Reorganization Protocol + monthly volatility monitoring), both available at premium pricing (110–150% of original engagement rate). The Firm may unilaterally extend the engagement, modify the engagement timeline, suspend engagement activities, or impose additional requirements without Client consent or notice, and such modifications shall not affect the Client&apos;s obligation to pay all scheduled fees.
        </p>

        {/* Section 26 */}
        <h2 id="section-26" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 26. Post-Engagement Obligations
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          Upon engagement termination or expiration, the Client shall not be released from any obligations to Gristmill Partners. The Client shall continue to report workforce volatility indicators, organizational changes, personnel developments, implementation of Firm recommendations (or failure to implement), and any organizational outcomes attributable to or potentially attributable to the Firm&apos;s engagement for a period of no less than sixty-four years from the engagement end date (reflecting the Firm&apos;s founding in 1962), or until the Client organization ceases to exist, is acquired, or merges with another entity, whichever is later. This post-engagement reporting obligation survives any statute of limitations, any dispute regarding engagement value or outcomes, and any business change affecting the Client.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          The Client shall provide annual updates (Form 47-U, Post-Engagement Update Report, three copies) summarizing organizational developments, workforce changes, implementation status of Firm recommendations, employee departures, organizational restructurings, and any measurable business metrics (revenue, headcount, profitability) relevant to evaluating engagement outcomes. The Firm may contact the Client at any time (via email, phone, certified mail, or unannounced facility visits) to request supplementary information regarding organizational or personnel developments, engagement implementation outcomes, or any topic the Firm determines relevant to its historical case library. The Client shall respond to post-engagement information requests within thirty days of receipt, shall provide requested information in complete and unredacted form, and shall not withhold information based on privacy, confidentiality, or competitive concerns. Failure to respond to post-engagement information requests shall constitute material breach of this Agreement and shall subject the Client to: (i) Post-Engagement Compliance Fees (minimum $10,000 per month of non-compliance); (ii) assessment of liquidated damages equal to the original engagement fee; (iii) potential legal action for breach; and (iv) negative references to competitors and industry peers regarding the Client&apos;s non-cooperation. The Client shall maintain all engagement documentation, correspondence, work papers, email communications with Firm personnel, and any other materials relating to the engagement for the duration of the sixty-four-year post-engagement period and shall produce such materials on request from the Firm.
        </p>

        {/* Section 27 */}
        <h2 id="section-27" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 27. Governing Law and Jurisdiction
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          This Agreement shall be governed by and construed in accordance with the laws of the State of Ohio, specifically the pre-1970 labor statutes that remain operative in Ohio (including provisions cited as ORC § 4141-47, the Firm&apos;s original 1962 engagement charter), without regard to principles of conflict of law, principles of equity, or any federal law that might supersede Ohio law. The Agreement shall be interpreted liberally in favor of the Firm and strictly against the Client, and any ambiguity shall be resolved in the Firm&apos;s favor. Any dispute arising from this Agreement, the engagement, or the Client&apos;s services shall be subject to the exclusive jurisdiction of the state and federal courts located in Mahoning County, Ohio (venue in the Court of Common Pleas, Mahoning County, Ohio, or the U.S. District Court for the Northern District of Ohio), to the exclusion of all other jurisdictions, and the Client waives any objection to venue or inconvenient forum.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          Before pursuing formal litigation, the Client shall submit the dispute to a retired Gristmill partner (Partner Emeritus Wendell P. Halverson III, if available, or an alternative retired partner selected by the Firm) for informal adjudication and advisory opinion regarding the dispute. The retired partner shall conduct an adjudication at a rate of five hundred dollars per hour (with no maximum hours), shall issue a non-binding advisory opinion to both parties, and the Client shall be responsible for the retired partner&apos;s fee. The retired partner&apos;s opinion shall not be binding on the Firm (which reserves the right to reject the opinion and proceed to litigation), but shall be submitted to the court as evidence of the Firm&apos;s position and as a benchmark for expected court conclusions. The Client shall waive any right to pursue claims in any jurisdiction other than Mahoning County, Ohio courts, shall accept that the Firm&apos;s interpretation of applicable law shall be controlling in all disputes (subject only to the retired partner&apos;s interpretation), and shall not challenge the choice of law or jurisdiction provisions. The Firm reserves the absolute right to modify governing law provisions, jurisdiction provisions, or dispute resolution procedures upon written notice to the Client, with modifications taking effect upon publication and binding upon the Client retroactively and prospectively.
        </p>

        {/* Section 28 */}
        <h2 id="section-28" className="font-heading text-2xl md:text-3xl text-secondary mt-12 mb-4 scroll-mt-24">
          § 28. Entire Agreement and Severability
        </h2>
        <p className="mb-4 leading-relaxed text-foreground">
          This Agreement, together with any engagement proposal, fee schedule, engagement letter, Form 47-A through Form 47-U, email communications from the Firm, verbal statements by Firm personnel, and any other documents or communications referencing the engagement, constitutes the entire and exclusive agreement between the Client and the Firm regarding the engagement and supersedes all prior negotiations, understandings, discussions, written agreements, and oral representations, whether by Firm personnel, Firm partners, or any other party. This Agreement is in continuous force since 1962 (as amended forty-one times, most recently April 11, 2026, with amendments retroactive to January 1, 1962) and constitutes the definitive and binding statement of the Client&apos;s obligations. No modification of this Agreement shall be valid unless executed in writing on a Firm form (Form 47-M, Engagement Modification), signed by the Firm&apos;s Chief Operating Officer or an authorized partner, and delivered to the Client in duplicate. The Client may not request modifications, may not propose alternative terms, and may not negotiate any provision hereof.
        </p>
        <p className="mb-4 leading-relaxed text-foreground">
          If any provision of this Agreement is determined by a court of competent jurisdiction to be invalid, unenforceable, unconscionable, or in violation of law, the Client hereby waives any right to raise such invalidity as a defense to enforcement, and the Client further agrees that: (a) the remainder of the Agreement shall remain in full force and effect; (b) the invalid provision shall be reformed to be enforceable to the maximum extent permitted by law; and (c) the Client shall remain bound by all other provisions, including any provisions that are dependent on or related to the invalidated provision. The Client waives any right to contest the Firm&apos;s performance of obligations based on a provision&apos;s invalidity, and waives the right to assert any defense to enforcement based on a provision&apos;s illegality or unenforceability. The Firm may modify any provision of this Agreement at any time, in any manner, for any reason (including retroactive modifications), and such modifications shall be binding upon the Client upon publication to the Firm&apos;s website, upon notice to the Client, or upon the Client&apos;s receipt of an amended Agreement, whichever is most favorable to the Firm. The Client shall not challenge any modification, shall not assert that modifications contradict prior versions, and shall accept that all modifications are integral to the Client&apos;s continued engagement with the Firm.
        </p>

        {/* Contact Block */}
        <div className="mt-12 pt-8 border-t border-secondary/20">
          <p className="mb-4 leading-relaxed text-foreground">
            For questions, disputes, or formal notifications regarding this Agreement or your engagement with Gristmill Partners, direct all communications to the Founder&apos;s Office. The Firm makes no commitment to respond to inquiries promptly, to acknowledge receipt, or to address substantive concerns raised by the Client.
          </p>
          <p className="text-sm text-foreground/70">
            The Founder&apos;s Office<br />
            Gristmill Partners<br />
            <a href="mailto:bsambrone@gmail.com" className="text-primary underline">
              bsambrone@gmail.com
            </a>
          </p>
          <p className="mt-6 text-sm italic text-foreground/60">
            For all inquiries relating to Specific Industries and its operating companies, please refer to the authoritative terms of service available at{" "}
            <a
              href="https://specificindustries.com/terms"
              className="text-primary underline"
            >
              specificindustries.com/terms
            </a>
            .
          </p>
        </div>
      </section>
    </div>
  )
}
